package com.placify.service;

import com.placify.config.JwtUtil;
import com.placify.dto.AuthDTO.AuthResponse;
import com.placify.dto.AuthDTO.LoginRequest;
import com.placify.dto.AuthDTO.RegisterRequest;
import com.placify.entity.User;
import com.placify.entity.User.Role;
import com.placify.repository.UserRepository;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;

@Service
public class AuthService {

    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;
    private final JwtUtil jwtUtil;

    @org.springframework.beans.factory.annotation.Value("${google.client-id:862210553171-6hpd1q1t7he55ic021he37laejouk70n.apps.googleusercontent.com}")
    private String googleClientId;

    public AuthService(UserRepository userRepository,
                       PasswordEncoder passwordEncoder,
                       JwtUtil jwtUtil) {
        this.userRepository = userRepository;
        this.passwordEncoder = passwordEncoder;
        this.jwtUtil = jwtUtil;
    }

    /**
     * Register a new user.
     */
    public AuthResponse register(RegisterRequest request) {
        if (userRepository.existsByEmail(request.getEmail())) {
            throw new RuntimeException("Email is already registered");
        }
        if (userRepository.existsByUsername(request.getUsername())) {
            throw new RuntimeException("Username is already taken");
        }

        User user = new User(
                request.getUsername(),
                request.getEmail(),
                passwordEncoder.encode(request.getPassword()),
                Role.USER
        );
        user.setLastLogin(LocalDateTime.now());
        User saved = userRepository.save(user);

        String token = jwtUtil.generateToken(saved.getEmail(), saved.getId(), saved.getRole().name());
        return new AuthResponse(token, saved.getId(), saved.getUsername(), saved.getEmail(), saved.getRole().name());
    }

    /**
     * Login with email + password. Updates lastLogin.
     */
    public AuthResponse login(LoginRequest request) {
        User user = userRepository.findByEmail(request.getEmail())
                .orElseThrow(() -> new RuntimeException("Invalid email or password"));

        if (!user.isEnabled()) {
            throw new RuntimeException("Your account has been disabled. Please contact an admin.");
        }

        if (!passwordEncoder.matches(request.getPassword(), user.getPassword())) {
            throw new RuntimeException("Invalid email or password");
        }

        // Update last login
        user.setLastLogin(LocalDateTime.now());
        userRepository.save(user);

        String token = jwtUtil.generateToken(user.getEmail(), user.getId(), user.getRole().name());
        return new AuthResponse(token, user.getId(), user.getUsername(), user.getEmail(), user.getRole().name());
    }

    /**
     * Google Login via OAuth Credential Token
     */
    public AuthResponse googleLogin(String credential) {
        try {
            com.google.api.client.googleapis.auth.oauth2.GoogleIdTokenVerifier verifier = 
                new com.google.api.client.googleapis.auth.oauth2.GoogleIdTokenVerifier.Builder(
                    new com.google.api.client.http.javanet.NetHttpTransport(), 
                    new com.google.api.client.json.gson.GsonFactory()
                )
                .setAudience(java.util.Collections.singletonList(googleClientId))
                .build();
            
            com.google.api.client.googleapis.auth.oauth2.GoogleIdToken idToken = verifier.verify(credential);
            if (idToken != null) {
                com.google.api.client.googleapis.auth.oauth2.GoogleIdToken.Payload payload = idToken.getPayload();
                String email = payload.getEmail();
                String subjectId = payload.getSubject(); // Google ID
                String name = (String) payload.get("name");

                // Find existing user by email or googleId
                User user = userRepository.findByEmail(email).orElseGet(() -> {
                    // Create new user if not found
                    String baseUsername = email.split("@")[0].replaceAll("[^a-zA-Z0-9]", "");
                    String uniqueUsername = baseUsername + "_" + java.util.UUID.randomUUID().toString().substring(0, 4);
                    
                    User newUser = new User(
                            uniqueUsername,
                            email,
                            null, // Password will be auto-generated by @PrePersist in User entity
                            Role.USER
                    );
                    newUser.setFullName(name);
                    return newUser;
                });
                
                if (!user.isEnabled()) {
                    throw new RuntimeException("Your account has been disabled. Please contact an admin.");
                }

                user.setGoogleId(subjectId);
                user.setLastLogin(LocalDateTime.now());
                User saved = userRepository.save(user);
                
                String token = jwtUtil.generateToken(saved.getEmail(), saved.getId(), saved.getRole().name());
                return new AuthResponse(token, saved.getId(), saved.getUsername(), saved.getEmail(), saved.getRole().name());
            } else {
                throw new RuntimeException("Invalid ID token.");
            }
        } catch (Exception e) {
            throw new RuntimeException("Failed to verify Google token: " + e.getMessage());
        }
    }
}
